# Generated by Django 6.0.2 on 2026-02-11 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='科目名')),
                ('code', models.CharField(max_length=5, verbose_name='科目コード')),
                ('total_video_count', models.PositiveIntegerField(default=0, verbose_name='動画総本数(本)')),
                ('total_question_count', models.PositiveIntegerField(default=0, verbose_name='問題総数(問)')),
            ],
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_type', models.CharField(choices=[('QA', 'Q-Assist'), ('QB', 'Question Bank'), ('OTHER', 'その他')], max_length=10, verbose_name='教材')),
                ('study_video_count', models.PositiveIntegerField(default=0, verbose_name='見た動画(本)')),
                ('study_time', models.PositiveIntegerField(default=0, verbose_name='学習時間(分)')),
                ('solve_count', models.PositiveIntegerField(default=0, verbose_name='演習問題数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.subject', verbose_name='科目')),
            ],
        ),
    ]
